apiVersion: v1
kind: Secret
metadata:
  name: rallly-secrets
  namespace: default
type: Opaque
stringData:
  # Database Connection String (postgres://user:password@service:port/db_name)
  DATABASE_URL: "postgres://rallly:change_me_password@postgres:5432/rallly"

  # Random string for encryption (generate with 'openssl rand -hex 32')
  SECRET_PASSWORD: "CHANGE_ME_TO_A_LONG_RANDOM_STRING"

  # NextAuth Secret (generate with 'openssl rand -base64 32')
  NEXTAUTH_SECRET: "CHANGE_ME_TO_A_LONG_RANDOM_STRING"

  # The email of the first admin user
  INITIAL_ADMIN_EMAIL: "admin@example.com"
