on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false

jobs:
  build:
    name: Build, push, and deploy
    #if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:

    - name: Set version from tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup tmate debug session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}

    - name: Build container image
      run: |
        docker build \
        --tag ghcr.io/m3nu/rallly:${{ env.RELEASE_VERSION }} \
        --tag ghcr.io/m3nu/rallly:latest \
        .
    - name: Container registry login
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      
    - name: Push image to GitHub
      if: github.ref == 'refs/heads/main'
      run: |
        docker push ghcr.io/m3nu/rallly:${{ env.RELEASE_VERSION }}
        docker push ghcr.io/m3nu/rallly:latest